window.QUESTIONS_BRANDS_BUSINESS = [
{ id: "bb001", topic: "brands_business", difficulty: 1, question: "Elon Musk acquired Twitter in 2022 and rebranded it. What is the platform now called?", answer: "X", accept: ["X", "x"], bid_eligible: false },
{ id: "bb002", topic: "brands_business", difficulty: 2, question: "Which Indian-origin CEO took over as head of Google and its parent company Alphabet in 2015?", answer: "Sundar Pichai", accept: ["Sundar Pichai", "sundar", "pichai"], bid_eligible: true },
{ id: "bb003", topic: "brands_business", difficulty: 2, question: "Which Indian payments infrastructure, adopted by Google Pay, PhonePe, and Paytm, stands for 'Unified Payments Interface'?", answer: "UPI", accept: ["UPI", "upi", "Unified Payments Interface"], bid_eligible: false },
{ id: "bb004", topic: "brands_business", difficulty: 3, question: "The documentary 'The Inventor: Out for Blood in Silicon Valley' covers the downfall of which health-tech company and its founder Elizabeth Holmes?", answer: "Theranos", accept: ["Theranos", "theranos"], bid_eligible: true },
{ id: "bb005", topic: "brands_business", difficulty: 1, question: "Which streaming platform, launched in 2007, revolutionised television watching?", answer: "Netflix", accept: ["Netflix", "netflix"], bid_eligible: false },
{ id: "bb006", topic: "brands_business", difficulty: 2, question: "OpenAI's ChatGPT launched in November 2022. Which company made a 10-billion-dollar investment into OpenAI in 2023?", answer: "Microsoft", accept: ["Microsoft", "microsoft"], bid_eligible: true },
{ id: "bb007", topic: "brands_business", difficulty: 3, question: "Mukesh Ambani's Reliance launched its 4G telecom service in 2016, disrupting India's sector. What is the brand called?", answer: "Jio", accept: ["Jio", "jio", "Reliance Jio"], bid_eligible: true },
{ id: "bb008", topic: "brands_business", difficulty: 2, question: "The viral 2010 film 'The Social Network' dramatises the founding of Facebook. Which actor plays Mark Zuckerberg?", answer: "Jesse Eisenberg", accept: ["Jesse Eisenberg", "eisenberg"], bid_eligible: false },
{ id: "bb009", topic: "brands_business", difficulty: 2, question: "BYJU'S, once India's most valuable edtech startup, was founded by Byju Raveendran in which year?", answer: "2011", accept: ["2011"], bid_eligible: false },
{ id: "bb010", topic: "brands_business", difficulty: 3, question: "The 2020–21 farmers' protests in India were against three farm laws. One of the laws dealt with contract farming. Name any one of the three laws.", answer: "Farmers' Produce Trade and Commerce Act", accept: ["FPTC", "trade and commerce act", "Essential Commodities Amendment", "contract farming act", "farmers produce", "price assurance act"], bid_eligible: true },
{ id: "bb011", topic: "brands_business", difficulty: 1, question: "Which food-delivery company was founded in India in 2010 and went public on Indian stock exchanges in 2021?", answer: "Zomato", accept: ["Zomato", "zomato"], bid_eligible: false },
{ id: "bb012", topic: "brands_business", difficulty: 2, question: "In 2023, which Indian conglomerate surpassed Reliance Industries to briefly become India's most valuable company by market cap?", answer: "Adani Group", accept: ["Adani", "adani group", "Gautam Adani"], bid_eligible: true },
];
