window.QUESTIONS_POP_CULTURE_INDIA = [
{ id: "pci001", topic: "pop_culture_india", difficulty: 1, question: "Which Indian OTT platform produced acclaimed originals like 'Mirzapur' and 'Panchayat'?", answer: "Amazon Prime Video", accept: ["Amazon Prime Video", "prime video", "amazon prime"], bid_eligible: false },
{ id: "pci002", topic: "pop_culture_india", difficulty: 1, question: "The Indian web series 'Sacred Games', the first Netflix original in India, starred which actor as Sartaj Singh?", answer: "Saif Ali Khan", accept: ["Saif Ali Khan", "saif ali khan", "saif"], bid_eligible: false },
{ id: "pci003", topic: "pop_culture_india", difficulty: 2, question: "Tanmay Bhat, Biswa Kalyan Rath, and Kanan Gill were co-founders of which Indian comedy collective?", answer: "All India Bakchod", accept: ["All India Bakchod", "AIB", "aib"], bid_eligible: true },
{ id: "pci004", topic: "pop_culture_india", difficulty: 3, question: "Which Bangalore-based stand-up comedian released the 2017 Netflix special 'Biswa Mast Aadmi'?", answer: "Biswa Kalyan Rath", accept: ["Biswa", "Biswa Kalyan Rath", "biswa"], bid_eligible: true },
{ id: "pci005", topic: "pop_culture_india", difficulty: 1, question: "The Indian reality show 'Bigg Boss' is hosted by which Bollywood star, associated with the show since its fourth season?", answer: "Salman Khan", accept: ["Salman Khan", "salman", "salman khan"], bid_eligible: false },
{ id: "pci006", topic: "pop_culture_india", difficulty: 2, men_mode_exclude: true, question: "Which Indian female rapper collaborates under the name 'Raja Kumari' and became one of the first Indian women to chart in the US rap scene?", answer: "Raja Kumari", accept: ["Raja Kumari", "raja kumari", "Svetha Yallapragada Rao"], bid_eligible: true },
{ id: "pci007", topic: "pop_culture_india", difficulty: 2, question: "Which 2022 Hindi series on Netflix followed a female lawyer defending a rape accused and sparked national conversation?", answer: "Delhi Crime", accept: ["Delhi Crime", "delhi crime", "Maamla Legal Hai"], bid_eligible: false },
{ id: "pci008", topic: "pop_culture_india", difficulty: 3, question: "The podcast 'The Seen and the Unseen' by Amit Varma is known for its long-form conversations. Approximately how long is a typical episode?", answer: "Three to four hours", accept: ["3-4 hours", "3 hours", "4 hours", "three hours", "very long"], bid_eligible: false },
{ id: "pci009", topic: "pop_culture_india", difficulty: 2, question: "Which Tamil-language crime thriller series, released on Amazon Prime in 2021, follows a cop investigating a serial killer and starred Prashanth in the lead?", answer: "Suzhal", accept: ["Suzhal", "suzhal", "Suzhal the Vortex"], bid_eligible: true },
{ id: "pci010", topic: "pop_culture_india", difficulty: 1, question: "Which Indian streaming platform produced the critically acclaimed series 'Scam 1992: The Harshad Mehta Story'?", answer: "SonyLIV", accept: ["SonyLIV", "sony liv", "sony"], bid_eligible: false },
{ id: "pci011", topic: "pop_culture_india", difficulty: 2, question: "Which Zakir Khan special on Amazon Prime popularised the phrase 'Sakht Launda' as a cultural touchstone for Indian millennial humour?", answer: "Haq Se Single", accept: ["Haq Se Single", "haq se single", "sakht launda"], bid_eligible: false },
{ id: "pci012", topic: "pop_culture_india", difficulty: 3, question: "Which Tamil YouTuber, known for political satire under the channel 'Madrasi', went viral for his cricket commentary parody videos?", answer: "Madrasi", accept: ["Madrasi", "madrasi", "Isaac Vettom"], bid_eligible: true },
];
