// Combined American (30%) + Indian (70%) memes pool
window.QUESTIONS_MEMES = [
// ── American ──
{ id: "meme_us001", topic: "memes", difficulty: 1, question: "'This is fine' — the iconic meme of a cartoon dog in a burning room — originated in a webcomic. Name it.", answer: "Gunshow", accept: ["Gunshow", "gunshow", "KC Green's Gunshow"], bid_eligible: false },
{ id: "meme_us002", topic: "memes", difficulty: 1, question: "The viral 'Ice Bucket Challenge' of 2014 raised over 115 million dollars for research into which disease?", answer: "ALS", accept: ["ALS", "als", "amyotrophic lateral sclerosis", "Lou Gehrig's disease"], bid_eligible: false },
{ id: "meme_us003", topic: "memes", difficulty: 2, question: "What is the name of the TikTok creator who actually created the 'Renegade' dance in 2019 — the dance later attributed to Charli D'Amelio?", answer: "Jalaiah Harmon", accept: ["Jalaiah Harmon", "jalaiah", "harmon"], bid_eligible: true },
{ id: "meme_us004", topic: "memes", difficulty: 2, question: "The 'Harlem Shake' meme went viral in 2013. Which DJ/producer released the original song?", answer: "Baauer", accept: ["Baauer", "baauer", "Harry Rodrigues"], bid_eligible: true },
// ── Indian ──
{ id: "meme_in001", topic: "memes", difficulty: 1, question: "The 'Rasode mein kaun tha' meme is from a scene in which Indian TV soap opera, where the phrase went absurdly viral in 2020?", answer: "Saath Nibhaana Saathiya", accept: ["Saath Nibhaana Saathiya", "saath nibhaana saathiya", "kokila", "rasode"], bid_eligible: true },
{ id: "meme_in002", topic: "memes", difficulty: 1, question: "The song 'Bachpan Ka Pyaar' went viral in 2021 after a video of a child singing it at a school function spread. Who sang the original track that was later remixed by Badshah?", answer: "Sahdev Dirdo", accept: ["Sahdev Dirdo", "sahdev", "sahdev dirdo"], bid_eligible: false },
{ id: "meme_in003", topic: "memes", difficulty: 1, question: "Which Dhinchak Pooja YouTube song from 2017, about a selfie addiction, became one of India's most memed songs?", answer: "Selfie Maine Leli Aaj", accept: ["Selfie Maine Leli Aaj", "selfie maine leli", "selfie aaj"], bid_eligible: true },
{ id: "meme_in004", topic: "memes", difficulty: 2, question: "The meme 'Rasode mein Kokila' launched which actress back into pop culture relevance in 2020?", answer: "Rupal Patel", accept: ["Rupal Patel", "rupal patel", "kokila"], bid_eligible: false },
{ id: "meme_in005", topic: "memes", difficulty: 2, question: "Which character from '3 Idiots' — the college director — became a meme symbol of toxic hustle culture and gatekeeping success?", answer: "Virus", accept: ["Virus", "virus", "Viru Sahastrabuddhe"], bid_eligible: true },
{ id: "meme_in006", topic: "memes", difficulty: 2, question: "Which Indian stand-up comedian's video 'Complaints' went mega-viral in 2018, launching him to mainstream fame?", answer: "Samay Raina", accept: ["Samay Raina", "samay raina", "samay"], bid_eligible: false },
{ id: "meme_in007", topic: "memes", difficulty: 3, question: "The term 'Chapri' entered Indian internet slang around 2018–2020. What does it generally mock?", answer: "Wannabe or low-budget cool", accept: ["wannabe", "low class", "chapri style", "trying to look cool", "fake style"], bid_eligible: true },
{ id: "meme_in008", topic: "memes", difficulty: 2, question: "The 'Pavri Ho Rahi Hai' meme originated from a video by a Pakistani creator. What is her name?", answer: "Dananeer Mobeen", accept: ["Dananeer Mobeen", "dananeer", "dananeer mobeen"], bid_eligible: false },
{ id: "meme_in009", topic: "memes", difficulty: 1, question: "Which viral UPSC aspirant's LinkedIn post about working 14-hour days and drinking 'discipline' became a widespread meme mocking toxic grind culture in India?", answer: "Shubham Gupta", accept: ["shubham gupta", "shubham", "UPSC linkedin guy"], bid_eligible: true },
{ id: "meme_in010", topic: "memes", difficulty: 3, question: "The 'bhai ne toh bol diya' meme format is associated with which Bollywood actor known for his straightforward screen presence in action films?", answer: "Salman Khan", accept: ["Salman Khan", "salman", "bhai"], bid_eligible: false },
{ id: "meme_in011", topic: "memes", difficulty: 2, question: "Which 2000s Bollywood film gave us the 'All izz well' meme that has endured for over a decade, typically used to express false reassurance?", answer: "3 Idiots", accept: ["3 Idiots", "three idiots", "3 idiots"], bid_eligible: false },
{ id: "meme_in012", topic: "memes", difficulty: 2, question: "'Yeh kya tha?' — a phrase used sarcastically to react to something absurd — is heavily associated with reactions to which IPL team's consistent underperformance?", answer: "Royal Challengers Bangalore", accept: ["RCB", "Royal Challengers Bangalore", "rcb"], bid_eligible: false },
];
