window.QUESTIONS_GLOBAL_LITERATURE = [
{ id: "gl001", topic: "global_literature", difficulty: 1, men_mode_exclude: true, question: "Chimamanda Ngozi Adichie's 2013 TED talk, later sampled by Beyoncé, is titled what?", answer: "We Should All Be Feminists", accept: ["We Should All Be Feminists", "we should all be feminists"], bid_eligible: false },
{ id: "gl002", topic: "global_literature", difficulty: 2, question: "Paul Beatty became the first American to win the Booker Prize in 2016. Name the winning novel.", answer: "The Sellout", accept: ["The Sellout", "the sellout"], bid_eligible: true },
{ id: "gl003", topic: "global_literature", difficulty: 2, men_mode_exclude: true, question: "Hanya Yanagihara's 2015 novel about four male friends and the trauma underpinning their friendship was a Booker finalist. Name it.", answer: "A Little Life", accept: ["A Little Life", "a little life"], bid_eligible: true },
{ id: "gl004", topic: "global_literature", difficulty: 3, question: "Ocean Vuong's 2019 debut novel, a letter from a Vietnamese-American son to his illiterate mother, is titled what?", answer: "On Earth We're Briefly Gorgeous", accept: ["On Earth We're Briefly Gorgeous", "briefly gorgeous"], bid_eligible: true },
{ id: "gl005", topic: "global_literature", difficulty: 1, men_mode_exclude: true, question: "Which Nigerian author wrote 'Purple Hibiscus' and 'Half of a Yellow Sun', set during the Biafran war?", answer: "Chimamanda Ngozi Adichie", accept: ["Chimamanda Ngozi Adichie", "chimamanda adichie", "adichie"], bid_eligible: false },
{ id: "gl006", topic: "global_literature", difficulty: 2, question: "The 2020 Booker Prize was won by a Scottish novel about a mother's dementia and a daughter's grief. Name it.", answer: "Shuggie Bain", accept: ["Shuggie Bain", "shuggie bain"], bid_eligible: true },
{ id: "gl007", topic: "global_literature", difficulty: 2, men_mode_exclude: true, question: "Ottessa Moshfegh's 2018 novel about a wealthy woman attempting to sleep for a year with help of prescription drugs is titled what?", answer: "My Year of Rest and Relaxation", accept: ["My Year of Rest and Relaxation", "my year of rest", "rest and relaxation"], bid_eligible: false },
{ id: "gl008", topic: "global_literature", difficulty: 3, men_mode_exclude: true, question: "Which Korean author won the Nobel Prize in Literature in 2024, becoming the first Asian woman to receive the honour?", answer: "Han Kang", accept: ["Han Kang", "han kang"], bid_eligible: true },
{ id: "gl009", topic: "global_literature", difficulty: 2, question: "Colson Whitehead's 'The Underground Railroad' won both the Pulitzer and the National Book Award in 2017. What is the Underground Railroad reimagined as in the novel?", answer: "A literal railroad with trains and tunnels", accept: ["literal railroad", "actual railroad", "real railroad", "underground train"], bid_eligible: false },
{ id: "gl010", topic: "global_literature", difficulty: 1, question: "Kazuo Ishiguro won the Nobel Prize in Literature in 2017. His 2021 novel imagines an artificial friend for a lonely girl. Name it.", answer: "Klara and the Sun", accept: ["Klara and the Sun", "klara and the sun", "klara"], bid_eligible: false },
{ id: "gl011", topic: "global_literature", difficulty: 3, question: "Which Zimbabwean writer's debut novel 'This Mournable Body' (2018), written in the second person, was shortlisted for the Booker Prize?", answer: "Tsitsi Dangarembga", accept: ["Tsitsi Dangarembga", "dangarembga"], bid_eligible: true },
{ id: "gl012", topic: "global_literature", difficulty: 2, question: "Douglas Stuart's 'Shuggie Bain' is set in which city during the Thatcher era?", answer: "Glasgow", accept: ["Glasgow", "glasgow"], bid_eligible: false },
];
