window.QUESTIONS_INDIAN_LITERATURE = [
{ id: "il001", topic: "indian_literature", difficulty: 1, question: "Which Indian-British author won the Booker Prize in 2008 for 'The White Tiger'?", answer: "Aravind Adiga", accept: ["Aravind Adiga", "aravind adiga", "adiga"], bid_eligible: false },
{ id: "il002", topic: "indian_literature", difficulty: 1, question: "Arundhati Roy's debut novel won the Booker Prize in 1997. What is it called?", answer: "The God of Small Things", accept: ["The God of Small Things", "god of small things"], bid_eligible: false },
{ id: "il003", topic: "indian_literature", difficulty: 2, men_mode_exclude: true, question: "Perumal Murugan's Tamil novel 'Madhorubagan', translated as 'One Part Woman', caused a major controversy in 2014–15. What was the central controversy?", answer: "The novel depicted ritualised sex at a temple festival and was protested by Hindu groups", accept: ["temple sex", "hindu groups", "religious protest", "caste and sexuality"], bid_eligible: true },
{ id: "il004", topic: "indian_literature", difficulty: 2, question: "Jeet Thayil's debut novel 'Narcopolis', set in Bombay's opium dens, was longlisted for the Booker Prize in which year?", answer: "2012", accept: ["2012"], bid_eligible: false },
{ id: "il005", topic: "indian_literature", difficulty: 3, men_mode_exclude: true, question: "Which Tamil Dalit writer's autobiography 'Karukku' is considered a landmark work of Dalit feminism?", answer: "Bama", accept: ["Bama", "bama", "Bama Faustina"], bid_eligible: true },
{ id: "il006", topic: "indian_literature", difficulty: 2, question: "Jerry Pinto's 2013 novel about a son caring for his mentally ill mother in Mumbai, which won the Hindu Literary Prize, is titled what?", answer: "Em and the Big Hoom", accept: ["Em and the Big Hoom", "em and the big hoom"], bid_eligible: false },
{ id: "il007", topic: "indian_literature", difficulty: 1, question: "Salman Rushdie's 2012 memoir about life in hiding after the fatwa against him is titled after a character from 'The Arabian Nights'. Name it.", answer: "Joseph Anton", accept: ["Joseph Anton", "joseph anton"], bid_eligible: false },
{ id: "il008", topic: "indian_literature", difficulty: 3, men_mode_exclude: true, question: "Which Indian poet published the landmark erotic autobiography 'My Story' (Ente Katha) in 1973 and wrote under the pen name 'Madhavikutty'?", answer: "Kamala Das", accept: ["Kamala Das", "kamala das", "Madhavikutty", "Kamala Surayya"], bid_eligible: true },
{ id: "il009", topic: "indian_literature", difficulty: 2, question: "Vikram Seth's 'A Suitable Boy' was adapted into a BBC miniseries in 2020. In which decade is the novel set?", answer: "1950s", accept: ["1950s", "1950", "fifties"], bid_eligible: false },
{ id: "il010", topic: "indian_literature", difficulty: 3, men_mode_exclude: true, question: "Meena Kandasamy's 2017 novel 'When I Hit You' deals with domestic violence and caste. It was longlisted for the Women's Prize for Fiction. In which city is she based?", answer: "Chennai", accept: ["Chennai", "Madras", "chennai"], bid_eligible: true },
{ id: "il011", topic: "indian_literature", difficulty: 1, question: "Chetan Bhagat's '2 States' is loosely autobiographical. His wife is from which state, creating the cultural conflict in the story?", answer: "Tamil Nadu", accept: ["Tamil Nadu", "tamil nadu", "South India", "Chennai"], bid_eligible: false },
{ id: "il012", topic: "indian_literature", difficulty: 2, question: "Which Assamese writer won the Sahitya Akademi Award in 2022 for her short story collection 'Baantar Bapoti'?", answer: "Arupa Patangia Kalita", accept: ["Arupa Patangia Kalita", "arupa patangia", "kalita"], bid_eligible: true },
];
