window.QUESTIONS_INDIAN_CINEMA = [
{ id: "ic001", topic: "indian_cinema", difficulty: 1, question: "S.S. Rajamouli's 2022 Telugu epic 'RRR' won the Golden Globe for Best Non-English Language Film. What does 'RRR' stand for?", answer: "Rise Roar Revolt", accept: ["Rise Roar Revolt", "rise roar revolt", "Roudram Ranam Rudhiram"], bid_eligible: false },
{ id: "ic002", topic: "indian_cinema", difficulty: 1, question: "The Oscar-winning song 'Naatu Naatu' from 'RRR' was composed by whom?", answer: "M. M. Keeravani", accept: ["M. M. Keeravani", "keeravani", "MM Keeravani"], bid_eligible: false },
{ id: "ic003", topic: "indian_cinema", difficulty: 2, question: "The 2022 Tamil film 'Ponniyin Selvan', directed by Mani Ratnam, is based on a novel by which author?", answer: "Kalki Krishnamurthy", accept: ["Kalki Krishnamurthy", "kalki", "Krishnamurthy"], bid_eligible: true },
{ id: "ic004", topic: "indian_cinema", difficulty: 2, question: "Which Malayalam film, directed by Lijo Jose Pellissery, won multiple National Awards in 2019 for its depiction of a local festival turned chaotic?", answer: "Jallikattu", accept: ["Jallikattu", "jallikattu"], bid_eligible: false },
{ id: "ic005", topic: "indian_cinema", difficulty: 3, question: "The Tamil film 'Visaranai' (2015), directed by Vetrimaaran and India's official submission for the Oscars, is based on a novel by which author?", answer: "Poomani", accept: ["Poomani", "poomani", "M. Chandrakumar"], bid_eligible: true },
{ id: "ic006", topic: "indian_cinema", difficulty: 1, question: "Who directed the 2006 film 'Rang De Basanti', which used a parallel narrative between freedom fighters and modern youth?", answer: "Rakeysh Omprakash Mehra", accept: ["Rakeysh Omprakash Mehra", "rakeysh mehra", "mehra"], bid_eligible: false },
{ id: "ic007", topic: "indian_cinema", difficulty: 2, question: "The Kannada film 'KGF: Chapter 1' became a pan-India blockbuster in 2018. Who plays the lead character Rocky Bhai?", answer: "Yash", accept: ["Yash", "yash", "Naveen Kumar Gowda"], bid_eligible: false },
{ id: "ic008", topic: "indian_cinema", difficulty: 2, question: "Vetri Maaran's 'Asuran' (2019) starring Dhanush was based on a novel by which Tamil author?", answer: "Poomani", accept: ["Poomani", "poomani"], bid_eligible: true },
{ id: "ic009", topic: "indian_cinema", difficulty: 3, question: "Which 2016 Marathi film, directed by Nagraj Manjule, starred Rinku Rajguru and Akash Thosar in a story of young love across caste lines?", answer: "Sairat", accept: ["Sairat", "sairat"], bid_eligible: true },
{ id: "ic010", topic: "indian_cinema", difficulty: 2, men_mode_exclude: true, question: "Which 2018 Malayalam film, starring Parvathy Thiruvothu and directed by Anjali Menon, opened dialogue around grief and female friendship?", answer: "Koode", accept: ["Koode", "koode"], bid_eligible: false },
{ id: "ic011", topic: "indian_cinema", difficulty: 1, question: "Which Tamil film by Pa. Ranjith starred Arya and explored caste discrimination in the context of boxing?", answer: "Sarpatta Parambarai", accept: ["Sarpatta Parambarai", "sarpatta"], bid_eligible: true },
{ id: "ic012", topic: "indian_cinema", difficulty: 3, question: "Adoor Gopalakrishnan's 'Pinneyum' was released in 2016. How many years had passed since his previous film?", answer: "Eight years", accept: ["8 years", "eight years", "8"], bid_eligible: true },
];
