window.QUESTIONS_WOMENS_HISTORY = [
{ id: "wh001", topic: "womens_history", difficulty: 1, men_mode_exclude: true, question: "In 2020, Kamala Harris made history when sworn in as US Vice President. What two historic firsts did she achieve?", answer: "First woman and first person of South Asian and Black heritage to serve as US Vice President", accept: ["first woman", "first Black woman", "first South Asian", "first woman VP", "first female vice president"], bid_eligible: false },
{ id: "wh002", topic: "womens_history", difficulty: 1, men_mode_exclude: true, question: "The MeToo movement went viral in 2017 after allegations against Harvey Weinstein. Who originally coined the phrase 'Me Too' in 2006?", answer: "Tarana Burke", accept: ["Tarana Burke", "tarana burke", "tarana"], bid_eligible: false },
{ id: "wh003", topic: "womens_history", difficulty: 2, men_mode_exclude: true, question: "The Shaheen Bagh protest in Delhi, led almost entirely by Muslim women, was against which law passed in 2019?", answer: "Citizenship Amendment Act", accept: ["Citizenship Amendment Act", "CAA", "caa"], bid_eligible: false },
{ id: "wh004", topic: "womens_history", difficulty: 2, men_mode_exclude: true, question: "Which Indian wrestler filed a complaint against Wrestling Federation of India chief Brij Bhushan Sharan Singh in 2023?", answer: "Vinesh Phogat", accept: ["Vinesh Phogat", "vinesh"], bid_eligible: true },
{ id: "wh005", topic: "womens_history", difficulty: 1, men_mode_exclude: true, question: "Malala Yousafzai became the youngest Nobel Peace Prize laureate in 2014. In which country was she born?", answer: "Pakistan", accept: ["Pakistan", "pakistan"], bid_eligible: false },
{ id: "wh006", topic: "womens_history", difficulty: 2, men_mode_exclude: true, question: "Which Indian law, passed in 2013 and often called the POSH Act, mandates Internal Complaints Committees for sexual harassment?", answer: "Sexual Harassment of Women at Workplace Act", accept: ["POSH Act", "POSH", "Sexual Harassment at Workplace Act", "2013 harassment law"], bid_eligible: false },
{ id: "wh007", topic: "womens_history", difficulty: 2, men_mode_exclude: true, question: "Greta Thunberg began her climate strike outside the Swedish parliament in 2018. How old was she when she started?", answer: "15", accept: ["15", "fifteen"], bid_eligible: false },
{ id: "wh008", topic: "womens_history", difficulty: 2, men_mode_exclude: true, question: "Irom Sharmila ended a 16-year hunger strike in 2016. What was she protesting against?", answer: "Armed Forces Special Powers Act", accept: ["AFSPA", "Armed Forces Special Powers Act", "armed forces act"], bid_eligible: true },
{ id: "wh009", topic: "womens_history", difficulty: 1, men_mode_exclude: true, question: "The 2012 Delhi gang rape case led to massive protests and legal reform. By what name is the victim known posthumously?", answer: "Nirbhaya", accept: ["Nirbhaya", "nirbhaya"], bid_eligible: false },
{ id: "wh010", topic: "womens_history", difficulty: 3, men_mode_exclude: true, question: "Which Indian feminist organisation, founded in 1980 by Indira Jaising, has fought landmark legal battles on domestic violence, maternity benefits, and sexual harassment?", answer: "Lawyers Collective", accept: ["Lawyers Collective", "lawyers collective"], bid_eligible: true },
{ id: "wh011", topic: "womens_history", difficulty: 2, men_mode_exclude: true, question: "Which Indian journalist published 'The Good Girls' (2021), investigating the 2014 Badaun gang rape case and police failures in UP?", answer: "Sonia Faleiro", accept: ["Sonia Faleiro", "sonia faleiro"], bid_eligible: true },
{ id: "wh012", topic: "womens_history", difficulty: 3, men_mode_exclude: true, question: "Which country held the world's first election where women could both vote and stand for parliament, in 1906?", answer: "Finland", accept: ["Finland", "finland"], bid_eligible: true },
];
