window.QUESTIONS_WORLD_CINEMA = [
{ id: "wc001", topic: "world_cinema", difficulty: 1, question: "Which South Korean film by Bong Joon-ho became the first non-English-language film to win the Academy Award for Best Picture, in 2020?", answer: "Parasite", accept: ["Parasite", "parasite", "Gisaengchung"], bid_eligible: false },
{ id: "wc002", topic: "world_cinema", difficulty: 1, question: "Alfonso Cuarón's 2018 black-and-white film, a love letter to his childhood housekeeper in Mexico City, won the Golden Lion at Venice and three Oscars. Name it.", answer: "Roma", accept: ["Roma", "roma"], bid_eligible: false },
{ id: "wc003", topic: "world_cinema", difficulty: 2, question: "The 2021 Danish film 'Flee' was nominated in three Oscar categories simultaneously — Best Documentary, Best Animated Feature, and Best International Feature Film. Who directed it?", answer: "Jonas Poher Rasmussen", accept: ["Jonas Poher Rasmussen", "rasmussen"], bid_eligible: true },
{ id: "wc004", topic: "world_cinema", difficulty: 3, question: "The French film 'Portrait of a Lady on Fire' (2019), directed by Céline Sciamma, won the Best Screenplay prize at Cannes. Who plays the painter Marianne?", answer: "Noémie Merlant", accept: ["Noémie Merlant", "noemie merlant"], bid_eligible: true },
{ id: "wc005", topic: "world_cinema", difficulty: 1, question: "The animated film 'Spirited Away' by Studio Ghibli won the 2003 Oscar for Best Animated Feature. Who directed it?", answer: "Hayao Miyazaki", accept: ["Hayao Miyazaki", "miyazaki"], bid_eligible: false },
{ id: "wc006", topic: "world_cinema", difficulty: 2, question: "Asghar Farhadi's 2011 Iranian film, which won the Oscar for Best Foreign Language Film, centres on a couple's divorce. What is it called?", answer: "A Separation", accept: ["A Separation", "a separation", "Jodaeiye Nader az Simin"], bid_eligible: true },
{ id: "wc007", topic: "world_cinema", difficulty: 3, question: "Which Senegalese filmmaker directed 'Atlantics' (2019), winning the Grand Prix at Cannes — making her the first Black woman to win a major prize there?", answer: "Mati Diop", accept: ["Mati Diop", "mati diop"], bid_eligible: true },
{ id: "wc008", topic: "world_cinema", difficulty: 2, question: "The 2023 Japanese animated film by Hayao Miyazaki won the Oscar for Best Animated Feature in 2024. Name it.", answer: "The Boy and the Heron", accept: ["The Boy and the Heron", "the boy and the heron", "How Do You Live"], bid_eligible: false },
{ id: "wc009", topic: "world_cinema", difficulty: 3, question: "Paul Verhoeven's 2021 film 'Benedetta', about a 17th-century Italian nun, starred which French actress in the lead role?", answer: "Virginie Efira", accept: ["Virginie Efira", "virginie efira"], bid_eligible: true },
{ id: "wc010", topic: "world_cinema", difficulty: 2, question: "Which 2019 South Korean film won the Palme d'Or at Cannes and went on to sweep the Oscars? Name the director.", answer: "Bong Joon-ho", accept: ["Bong Joon-ho", "bong joon ho", "bong"], bid_eligible: false },
{ id: "wc011", topic: "world_cinema", difficulty: 2, question: "Cate Blanchett won her second Best Actress Oscar for playing a conductor in the 2022 film 'Tár'. Who directed the film?", answer: "Todd Field", accept: ["Todd Field", "todd field"], bid_eligible: false },
{ id: "wc012", topic: "world_cinema", difficulty: 3, question: "Which Iranian director made 'The Salesman' (2016), which won the Oscar for Best Foreign Language Film and explores the aftermath of a home invasion?", answer: "Asghar Farhadi", accept: ["Asghar Farhadi", "farhadi"], bid_eligible: true },
];
