window.QUESTIONS_INDIAN_POLITICS = [
{ id: "ip001", topic: "indian_politics", difficulty: 1, question: "Which Indian Prime Minister declared a national Emergency in 1975, suspending civil liberties for 21 months?", answer: "Indira Gandhi", accept: ["Indira Gandhi", "indira gandhi", "indira"], bid_eligible: false },
{ id: "ip002", topic: "indian_politics", difficulty: 1, question: "The Bharatiya Janata Party won a majority in the 2014 Indian general elections, making which leader Prime Minister for the first time?", answer: "Narendra Modi", accept: ["Narendra Modi", "modi", "narendra modi"], bid_eligible: false },
{ id: "ip003", topic: "indian_politics", difficulty: 2, question: "Article 370 granted special status to which state — status revoked by the central government in August 2019?", answer: "Jammu and Kashmir", accept: ["Jammu and Kashmir", "jammu kashmir", "kashmir", "J&K"], bid_eligible: true },
{ id: "ip004", topic: "indian_politics", difficulty: 2, question: "The 2020–2021 farmers' protests in India were followed by what outcome in November 2021?", answer: "Repeal of the farm laws", accept: ["repeal", "the laws were repealed", "farm laws repealed", "withdrawal"], bid_eligible: true },
{ id: "ip005", topic: "indian_politics", difficulty: 3, question: "Which political party did Arvind Kejriwal found in 2012 on an anti-corruption platform?", answer: "Aam Aadmi Party", accept: ["Aam Aadmi Party", "AAP", "aap"], bid_eligible: false },
{ id: "ip006", topic: "indian_politics", difficulty: 2, question: "The Citizenship Amendment Act (2019) provides a path to citizenship for refugees from three neighbouring countries, but notably excludes which religion?", answer: "Islam", accept: ["Islam", "islam", "Muslims", "Muslim"], bid_eligible: true },
{ id: "ip007", topic: "indian_politics", difficulty: 1, men_mode_exclude: true, question: "Who was India's first female President, elected in 2007?", answer: "Pratibha Patil", accept: ["Pratibha Patil", "pratibha patil", "pratibha"], bid_eligible: false },
{ id: "ip008", topic: "indian_politics", difficulty: 3, question: "The 'Mandal Commission' report, implemented in 1990 under V.P. Singh, recommended reservations for which category?", answer: "Other Backward Classes", accept: ["OBC", "other backward classes", "backward classes"], bid_eligible: true },
{ id: "ip009", topic: "indian_politics", difficulty: 3, question: "The Pokhran-II nuclear tests of 1998 were conducted under which Prime Minister's government?", answer: "Atal Bihari Vajpayee", accept: ["Vajpayee", "Atal Bihari Vajpayee", "atal bihari vajpayee"], bid_eligible: true },
{ id: "ip010", topic: "indian_politics", difficulty: 2, question: "The Supreme Court of India legalised which act between consenting adults in 2018, striking down Section 377?", answer: "Homosexuality", accept: ["homosexuality", "gay sex", "same-sex relations", "consensual same-sex activity"], bid_eligible: false },
{ id: "ip011", topic: "indian_politics", difficulty: 1, men_mode_exclude: true, question: "Which woman leader became Chief Minister of West Bengal in 2011, ending 34 years of Left Front rule?", answer: "Mamata Banerjee", accept: ["Mamata Banerjee", "mamata", "didi"], bid_eligible: false },
{ id: "ip012", topic: "indian_politics", difficulty: 2, question: "Which Indian political leader was the Chief Minister of Gujarat during the 2002 Gujarat riots?", answer: "Narendra Modi", accept: ["Narendra Modi", "modi"], bid_eligible: false },
];
