window.QUESTIONS_POP_CULTURE_WEST = [
{ id: "pcw001", topic: "pop_culture_west", difficulty: 1, question: "Which HBO series, based on a graphic novel about commodified superheroes, premiered in 2019?", answer: "Watchmen", accept: ["Watchmen", "watchmen"], bid_eligible: false },
{ id: "pcw002", topic: "pop_culture_west", difficulty: 1, question: "'Keeping Up with the Kardashians' aired its final episode in 2021 after how many seasons?", answer: "20", accept: ["20", "twenty"], bid_eligible: false },
{ id: "pcw003", topic: "pop_culture_west", difficulty: 2, question: "The 2023 film 'Barbie', directed by Greta Gerwig, became the highest-grossing film ever directed by a woman. Approximately how much did it gross worldwide?", answer: "1.4 billion dollars", accept: ["1.4 billion", "1.44 billion", "over a billion"], bid_eligible: true },
{ id: "pcw004", topic: "pop_culture_west", difficulty: 2, question: "Which American TV show about a chemistry teacher turned drug kingpin ran on AMC from 2008 to 2013?", answer: "Breaking Bad", accept: ["Breaking Bad", "breaking bad"], bid_eligible: false },
{ id: "pcw005", topic: "pop_culture_west", difficulty: 3, question: "'The White Lotus' Season 2 (2022) was set in which Italian island, exploring class and desire among wealthy tourists?", answer: "Sicily", accept: ["Sicily", "sicily"], bid_eligible: true },
{ id: "pcw006", topic: "pop_culture_west", difficulty: 2, men_mode_exclude: true, question: "The 'Eras Tour' by Taylor Swift in 2023–2024 became the highest-grossing concert tour in history. Approximately how much did it gross?", answer: "Over 1 billion dollars", accept: ["1 billion", "over a billion", "1.04 billion", "billion"], bid_eligible: true },
{ id: "pcw007", topic: "pop_culture_west", difficulty: 3, question: "Which 2019 limited series on HBO starred Billy Porter as Pray Tell and explored LGBTQ+ identity and Harlem ballroom culture?", answer: "Pose", accept: ["Pose", "pose"], bid_eligible: true },
{ id: "pcw008", topic: "pop_culture_west", difficulty: 1, question: "In which year did the original 'RuPaul's Drag Race' premiere?", answer: "2009", accept: ["2009", "two thousand nine"], bid_eligible: false },
{ id: "pcw009", topic: "pop_culture_west", difficulty: 3, question: "The game 'Elden Ring', developed with writer George R.R. Martin, won Game of the Year in 2022. Which Japanese studio made it?", answer: "FromSoftware", accept: ["FromSoftware", "from software", "fromsoftware"], bid_eligible: true },
{ id: "pcw010", topic: "pop_culture_west", difficulty: 2, question: "Which 2021 Netflix show about a widowed Korean immigrant woman playing a high-stakes game for survival became a global sensation?", answer: "Squid Game", accept: ["Squid Game", "squid game"], bid_eligible: false },
{ id: "pcw011", topic: "pop_culture_west", difficulty: 2, question: "Which 2019 HBO show starring Nicole Kidman and Meryl Streep was an adaptation of Liane Moriarty's novel 'Big Little Lies' follow-up? Actually — what is the title of the second season?", answer: "Big Little Lies Season 2", accept: ["Big Little Lies", "big little lies"], bid_eligible: false },
{ id: "pcw012", topic: "pop_culture_west", difficulty: 3, question: "The podcast 'My Favorite Murder', which blends true crime with comedy, was hosted by which two women?", answer: "Karen Kilgariff and Georgia Hardstark", accept: ["Karen Kilgariff", "Georgia Hardstark", "kilgariff", "hardstark"], bid_eligible: true },
];
