window.QUESTIONS_SPORTS = [
{ id: "sp001", topic: "sports", difficulty: 1, question: "At the 2020 Tokyo Olympics, Neeraj Chopra became the first Indian to win an Olympic gold medal in athletics. In which event?", answer: "Javelin throw", accept: ["Javelin throw", "javelin"], bid_eligible: false },
{ id: "sp002", topic: "sports", difficulty: 1, question: "Which tennis player holds the record for most Grand Slam singles titles as of 2024, with 24?", answer: "Novak Djokovic", accept: ["Novak Djokovic", "djokovic", "novak"], bid_eligible: false },
{ id: "sp003", topic: "sports", difficulty: 2, question: "Simone Biles withdrew from multiple events at the 2020 Tokyo Olympics citing mental health, then returned at Paris 2024. How many gold medals did she win in Paris?", answer: "Three", accept: ["3", "three"], bid_eligible: true },
{ id: "sp004", topic: "sports", difficulty: 2, question: "The 2022 FIFA World Cup was held in which country — the first Middle Eastern nation to host the tournament?", answer: "Qatar", accept: ["Qatar", "qatar"], bid_eligible: false },
{ id: "sp005", topic: "sports", difficulty: 3, question: "Caster Semenya has been at the centre of a legal battle over testosterone regulations. Which governing body enforced the limits affecting her eligibility?", answer: "World Athletics", accept: ["World Athletics", "world athletics", "IAAF"], bid_eligible: true },
{ id: "sp006", topic: "sports", difficulty: 1, question: "Which Indian batter became the fastest in history to reach 8,000 Test runs?", answer: "Virat Kohli", accept: ["Virat Kohli", "kohli", "virat"], bid_eligible: false },
{ id: "sp007", topic: "sports", difficulty: 2, question: "The 2023 ICC Cricket World Cup was held in India. Which team won the tournament, defeating India in the final?", answer: "Australia", accept: ["Australia", "australia"], bid_eligible: false },
{ id: "sp008", topic: "sports", difficulty: 2, question: "Naomi Osaka won four Grand Slam titles before 25. In which city was she born?", answer: "Osaka", accept: ["Osaka", "osaka"], bid_eligible: true },
{ id: "sp009", topic: "sports", difficulty: 1, question: "In which year did India win the T20 Cricket World Cup, defeating South Africa in the final in Barbados?", answer: "2024", accept: ["2024"], bid_eligible: false },
{ id: "sp010", topic: "sports", difficulty: 2, men_mode_exclude: false, question: "PV Sindhu became the first Indian woman to win two Olympic medals in badminton. At which Olympics did she win her second medal?", answer: "Tokyo 2020", accept: ["Tokyo", "2020", "Tokyo 2020", "2021"], bid_eligible: false },
{ id: "sp011", topic: "sports", difficulty: 3, question: "Which Formula 1 driver won the World Drivers' Championship in 2021 after a controversial final lap at the Abu Dhabi Grand Prix?", answer: "Max Verstappen", accept: ["Max Verstappen", "verstappen", "max"], bid_eligible: true },
{ id: "sp012", topic: "sports", difficulty: 2, question: "Which Indian wrestler filed a complaint against the Wrestling Federation of India chief Brij Bhushan Sharan Singh in 2023, sparking a months-long protest at Jantar Mantar?", answer: "Vinesh Phogat", accept: ["Vinesh Phogat", "vinesh", "bajrang punia", "sakshi malik"], bid_eligible: true },
];
