// Standalone bid pool — all questions are bid_eligible by default (set in app.js)
// Deliberately harder, with satisfying "aha" answers
window.QUESTIONS_BID = [
{ id: "bid001", topic: "bid", difficulty: 2, question: "This Grammy-winning song was the first Hindi-language track to chart on the Billboard Hot 100. Released in 2021, it was a collaboration between Doja Cat and a Punjabi artist. Name the song.", answer: "Need to Know", accept: ["Need to Know", "need to know"], bid_eligible: true },
{ id: "bid002", topic: "bid", difficulty: 2, question: "Which architect designed the Serpentine Pavilion in 2018 — the first Indian architect commissioned to do so — known for his work on the Indian pavilions at Venice?", answer: "Pritzker Prize", accept: ["Balkrishna Doshi", "BV Doshi", "doshi"], bid_eligible: true },
{ id: "bid003", topic: "bid", difficulty: 3, question: "The 2020 film 'Mank', directed by David Fincher, is about the writing of which classic screenplay?", answer: "Citizen Kane", accept: ["Citizen Kane", "citizen kane"], bid_eligible: true },
{ id: "bid004", topic: "bid", difficulty: 2, question: "Which Indian sprinter won India's first ever World Athletics Championships medal in 2023, taking silver in the 400m hurdles?", answer: "Neeraj Chopra", accept: ["Neeraj Chopra", "neeraj"], bid_eligible: true },
{ id: "bid005", topic: "bid", difficulty: 3, question: "Which musician composed 'All I Want for Christmas Is You' — and in which year was it released?", answer: "Mariah Carey, 1994", accept: ["Mariah Carey", "mariah carey", "1994"], bid_eligible: true },
{ id: "bid006", topic: "bid", difficulty: 2, question: "The term 'stan' — meaning an obsessive fan — derives from a 2000 Eminem song. Who is Stan in the song?", answer: "An obsessive fan who writes letters to Eminem", accept: ["obsessive fan", "stan is a fan", "eminem fan", "he writes letters"], bid_eligible: true },
{ id: "bid007", topic: "bid", difficulty: 3, question: "Which Indian novelist's 2021 book 'A Passage North' was longlisted for the Booker Prize and follows a young man travelling to northern Sri Lanka?", answer: "Anuk Arudpragasam", accept: ["Anuk Arudpragasam", "arudpragasam", "anuk"], bid_eligible: true },
{ id: "bid008", topic: "bid", difficulty: 2, question: "In 2022, the James Webb Space Telescope released its first images. Which country operates it jointly with ESA and CSA?", answer: "United States", accept: ["USA", "United States", "America", "NASA"], bid_eligible: true },
{ id: "bid009", topic: "bid", difficulty: 3, question: "Which Thai filmmaker directed 'Uncle Boonmee Who Can Recall His Past Lives', which won the Palme d'Or at Cannes in 2010?", answer: "Apichatpong Weerasethakul", accept: ["Apichatpong Weerasethakul", "apichatpong", "joe"], bid_eligible: true },
{ id: "bid010", topic: "bid", difficulty: 2, question: "Beyoncé's 2022 album 'Renaissance' paid tribute to which subculture, widely credited to Black and queer communities?", answer: "Ballroom and house music", accept: ["ballroom", "house music", "Black queer culture", "dance music", "vogue"], bid_eligible: true },
{ id: "bid011", topic: "bid", difficulty: 3, question: "Which Indian economist won the Nobel Memorial Prize in Economic Sciences in 2019, sharing it with Abhijit Banerjee and Michael Kremer?", answer: "Esther Duflo", accept: ["Esther Duflo", "esther duflo", "duflo"], bid_eligible: true },
{ id: "bid012", topic: "bid", difficulty: 2, question: "The 2023 Indian film 'Jailer', directed by Nelson Dilipkumar, stars which actor in the titular role?", answer: "Rajinikanth", accept: ["Rajinikanth", "rajinikanth", "rajini"], bid_eligible: true },
];
