window.QUESTIONS_QUEER_CULTURE = [
{ id: "qc001", topic: "queer_culture", difficulty: 1, men_mode_exclude: true, question: "Which Supreme Court of India judgment in 2018 decriminalised homosexuality by reading down Section 377? Name the case by its petitioner.", answer: "Navtej Singh Johar vs Union of India", accept: ["Navtej Singh Johar", "navtej johar", "377 judgment", "section 377"], bid_eligible: false },
{ id: "qc002", topic: "queer_culture", difficulty: 1, question: "Which organisation is credited with popularising the slogan 'We're here, we're queer, get used to it'?", answer: "Queer Nation", accept: ["Queer Nation", "queer nation"], bid_eligible: false },
{ id: "qc003", topic: "queer_culture", difficulty: 2, men_mode_exclude: true, question: "Which Indian film by Onir (2011) was the first mainstream Hindi film with an openly gay protagonist, self-funded after producers pulled out?", answer: "I Am", accept: ["I Am", "i am"], bid_eligible: true },
{ id: "qc004", topic: "queer_culture", difficulty: 2, question: "The Stonewall Inn, site of the 1969 uprising that catalysed the modern LGBTQ+ rights movement, is located in which New York City neighbourhood?", answer: "Greenwich Village", accept: ["Greenwich Village", "greenwich village", "West Village"], bid_eligible: false },
{ id: "qc005", topic: "queer_culture", difficulty: 3, question: "Which Indian activist and lawyer founded the Naz Foundation that originally filed the petition challenging Section 377 in the Delhi High Court?", answer: "Anjali Gopalan", accept: ["Anjali Gopalan", "anjali gopalan"], bid_eligible: true },
{ id: "qc006", topic: "queer_culture", difficulty: 1, question: "The rainbow flag, the most recognised symbol of LGBTQ+ pride, was designed in 1978 by which artist and activist?", answer: "Gilbert Baker", accept: ["Gilbert Baker", "gilbert baker"], bid_eligible: false },
{ id: "qc007", topic: "queer_culture", difficulty: 2, question: "The American series 'Pose', which featured the largest cast of transgender actors in TV history, was set in which decade's ballroom culture?", answer: "1980s", accept: ["1980s", "80s", "eighties"], bid_eligible: false },
{ id: "qc008", topic: "queer_culture", difficulty: 3, question: "Which country was the first in Asia to legalise same-sex marriage, doing so in 2019?", answer: "Taiwan", accept: ["Taiwan", "taiwan"], bid_eligible: true },
{ id: "qc009", topic: "queer_culture", difficulty: 2, question: "The annual pride parade in Mumbai was held for the first time in which year?", answer: "2008", accept: ["2008", "two thousand eight"], bid_eligible: false },
{ id: "qc010", topic: "queer_culture", difficulty: 3, men_mode_exclude: true, question: "Which Indian trans activist from Tamil Nadu became one of the first trans ward councillors in India in 2021?", answer: "Vijayalakshmi", accept: ["Vijayalakshmi", "vijayalakshmi"], bid_eligible: true },
{ id: "qc011", topic: "queer_culture", difficulty: 1, question: "Which streaming platform produced 'Disclosure' (2020), examining Hollywood's history of transgender representation, narrated by Laverne Cox?", answer: "Netflix", accept: ["Netflix", "netflix"], bid_eligible: false },
{ id: "qc012", topic: "queer_culture", difficulty: 2, men_mode_exclude: true, question: "Which 2021 film directed by Jane Campion featured Kristen Stewart as Diana Spencer and was widely discussed for its queer subtext?", answer: "Spencer", accept: ["Spencer", "spencer"], bid_eligible: true },
];
